name: Python Tests, Linting, and TODO Tracking

on:
  push:
    branches:
      - main
      - feature/update-structureAndTesting
      - feature/Refactoring
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: pytest --cov=pathfinding_algorithms --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Display .flake8 config
        run: cat .flake8

      - name: Check flake8 version
        run: flake8 --version

      - name: Lint code with flake8
        run: flake8 --config=.flake8 .

      - name: Format code with black
        run: black --check .

  todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create issues from TODO
        uses: alstr/todo-to-issue-action@v5.1.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
