name: Python Tests and Linting

on:
  push:
    branches:
      - feature/update-structureAndTesting 
  pull_request:
    branches:
      - feature/update-structureAndTesting 

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pylint

      - name: Run tests with coverage
        run: pytest --cov=. test_algorithms.py

      - name: Run pylint
        run: |
          pylint algorithms.py graph_utils.py main.py test_algorithms.py
